export const ACTIONS = {
	SET_RECORDING: 'SET_RECORDING',
	SET_SCREEN_AND_AUDIO_STREAM: 'SET_SCREEN_AND_AUDIO_STREAM',
	SET_CAMERA_AND_MIC_STREAM: 'SET_CAMERA_AND_MIC_STREAM',
	
	SET_RECORDING_STATE: 'SET_RECORDING_STATE',
	START_RECORDING: 'START_RECORDING',
	STOP_RECORDING: 'STOP_RECORDING',
	END_RECORDING: 'END_RECORDING',
	PAUSE_RECORDING: 'PAUSE_RECORDING',
	CONTINUE_RECORDING: 'CONTINUE_RECORDING',

	SET_RECORDING_OPTIONS: 'SET_RECORDING_OPTIONS',
	SET_MULTIMEDIA: 'SET_MULTIMEDIA',

	SET_CONFIG: 'SET_CONFIG',

	SET_IS_RECORDING: 'SET_IS_RECORDING',
	SET_MEDIA_RECORDER: 'SET_MEDIA_RECORDER',
	SET_MEDIA: 'SET_MEDIA',

	SET_FRAME_RATE: 'SET_FRAME_RATE',
	SET_RESOLUTION: 'SET_RESOLUTION',
	SET_QUALITY: 'SET_QUALITY',
	SET_FILE_TYPE: 'SET_FILE_TYPE',
};

export const RECORDING_STATE = {
	INACTIVE: 'inactive',
	PAUSED: 'paused',
	STOPED: 'stoped',
	RECORDING: 'recording',
};
