export const ACTIONS = {
	SET_RECORDING: 'SET_RECORDING',
	SET_SCREEN_AND_AUDIO_STREAM: 'SET_SCREEN_AND_AUDIO_STREAM',
	SET_CAMERA_AND_MIC_STREAM: 'SET_CAMERA_AND_MIC_STREAM',
	START_RECORDING: 'START_RECORDING',
	END_RECORDING: 'END_RECORDING',
	PAUSE_RECORDING: 'PAUSE_RECORDING',
	CONTINUE_RECORDING: 'CONTINUE_RECORDING',

	SET_RECORDING_OPTIONS: 'SET_RECORDING_OPTIONS',
	SET_AUDIO: 'SET_AUDIO',
	SET_SCREEN: 'SET_SCREEN',
	SET_CAMERA: 'SET_CAMERA',
	SET_MIC: 'SET_MIC',

	SET_IS_RECORDING: 'SET_IS_RECORDING',
	SET_MEDIA_RECORDER: 'SET_MEDIA_RECORDER',
	SET_MEDIA: 'SET_MEDIA',

	SET_FRAME_RATE: 'SET_FRAME_RATE',
	SET_RESOLUTION: 'SET_RESOLUTION',
	SET_QUALITY: 'SET_QUALITY',
	SET_CODEC: 'SET_CODEC',
	SET_FILE_TYPE: 'SET_FILE_TYPE',
	SET_AUDIO_BIT_RATE: 'SET_AUDIO_BIT_RATE',
	SET_VIDEO_BIT_RATE: 'SET_VIDEO_BIT_RATE',
};
